name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt install python3-pip
          pip install -r requirements.txt
          pip install tox

      - name: Run tests
        run: tox
        env:
          TOXENV: py

      - name: Check for tox configuration
        run: |
          if ! grep -q '\[tox\]' setup.cfg; then
            echo "[tox] section not found in setup.cfg"
            exit 1
          fi
