name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched to avoid shallow clone issues

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade setuptools
        run: |
          python -m pip install --upgrade setuptools

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage codecov

      - name: Run tests
        run: |
          python setup.py develop
          coverage run -m unittest discover

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: codecov
