name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes pytest pytest-doctestplus

      - name: Lint with pyflakes
        run: pyflakes .

      - name: Compile Python files
        run: python -We:invalid -We::SyntaxWarning -m compileall -f -q removestar/

      - name: Test with pytest
        run: pytest

      - name: Ensure readme.md exists
        run: echo "# Project Title" > readme.md

      - name: Install package
        run: python setup.py install
