name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9']
        arch: [x64]  # Removed arm64 as it may not be supported for all Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: pip install -r dev-requirements.txt

    - name: Clean
      run: make clean

    - name: Run PEP8
      run: make pep8

    - name: Run Flake8
      run: make flake8

    - name: Run Check
      run: make check

    - name: Run Unit Tests
      run: make unittest

    - name: Upload coverage to Coveralls
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
